name: ms_dart
description: Tiny milisecond conversion utility
version: 1.0.1
homepage: https://github.com/chrisvasquez/ms_dart
author: Chris Vasquez <chris@teamvasquez.org>

environment:
  sdk: ">=2.5.0 <3.0.0"

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
