name: ms_dart
description: Tiny milisecond conversion utility. With two static methods.  One converts the number of milliseconds to a string representation rounded to the closes smallest measure of time. The other converts a string representation fo time to the number of milliseconds.
version: 1.0.2
homepage: https://github.com/chrisvasquez/ms_dart
author: Chris Vasquez <chris@teamvasquez.org>

environment:
  sdk: ">=2.5.0 <3.0.0"

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
